#!/usr/bin/env bash

# variables
RESET = \e[0m
GREEN = \e[92m

# main
echo "[i] Running cmake script.. (verbose: cmake -G Ninja -B ./out)"
cmake -G Ninja -B ./out
echo "[i] Running ninja script.. (verbose: ninja -C ./out)"
ninja -C ./out
echo "[i] Copying files... (verbose: cp ./out/compile_commands.json ."
cp ./out/compile_commands.json .
echo "${GREEN}[+] Build done!${RESET}"
