#!/usr/bin/env bash

# main
echo "[i] Running cmake script.. (verbose: cmake -G Ninja -B ./out)"
cmake -G Ninja -B ./out
echo "[i] Running ninja script.. (verbose: ninja -C ./out)"
ninja -C ./out
echo "[i] Copying files... (verbose: cp ./out/compile_commands.json ."
cp ./out/compile_commands.json .
echo "Build done!"